spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://receiptdatabase:5433/receipt
    driver-class-name: org.postgresql.Driver
grpc:
  client:
    billing-service:
      address: static://billing-service:9092
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext