server:
  port: 8092
spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/receipt
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    password: "some password" # some chars...
    port: 587
    username: "email here" #email address...
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
grpc:
  server:
    port: 9092