server:
  port: 8091

spring:
  application:
    name: core-service
  profiles:
    default: dev
  flyway:
    locations: classpath:db/migration
  rabbitmq:
    password: rmpassword
    port: 5672
    username: rmuser

broker:
#  profile: "rabbit"
  profile: "rest"

destinations:
  queues:
    participant:
      queue: core
      routing-key: create
  topics:
    participant:
      exchange: participant
      routing-key: create

transaction:
  profile: events
#  profile: camunda

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  default-serialization-format: application/json

scheduled-tasks:
  transfer-outbox: "0/30 * * ? * *"